<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_guide_admin' => [[], ['_controller' => 'App\\Controller\\GuideAdminController::index'], [], [['text', '/guide/admin']], [], []],
    'app_guide_index' => [[], ['_controller' => 'App\\Controller\\GuideController::index'], [], [['text', '/guide/']], [], []],
    'app_guide_new' => [[], ['_controller' => 'App\\Controller\\GuideController::new'], [], [['text', '/guide/new']], [], []],
    'app_guide_show' => [['id'], ['_controller' => 'App\\Controller\\GuideController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/guide']], [], []],
    'app_guide_edit' => [['id'], ['_controller' => 'App\\Controller\\GuideController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/guide']], [], []],
    'app_guide_delete' => [['id'], ['_controller' => 'App\\Controller\\GuideController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/guide']], [], []],
    'app_upcomingevents_admin' => [[], ['_controller' => 'App\\Controller\\UpcomingeventsAdminController::index'], [], [['text', '/admin/upcomingevents']], [], []],
    'app_upcomingevents_index' => [[], ['_controller' => 'App\\Controller\\UpcomingeventsController::index'], [], [['text', '/upcomingevents/all']], [], []],
    'app_upcomingevents_new' => [[], ['_controller' => 'App\\Controller\\UpcomingeventsController::new'], [], [['text', '/upcomingevents/new']], [], []],
    'app_upcomingevents_show' => [['id'], ['_controller' => 'App\\Controller\\UpcomingeventsController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/upcomingevents']], [], []],
    'app_upcomingevents_edit' => [['id'], ['_controller' => 'App\\Controller\\UpcomingeventsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/upcomingevents']], [], []],
    'app_upcomingevents_delete' => [['id'], ['_controller' => 'App\\Controller\\UpcomingeventsController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id'], ['text', '/upcomingevents']], [], []],
];
